#!/bin/bash

TEMP_DIR="$(mktemp -d)"

for i in "$@"; do  
  # Random user agent
  UA=$(head -$((${RANDOM} % `wc -l < $(dirname "${BASH_SOURCE[0]}")/useragents.txt` + 1)) $(dirname "${BASH_SOURCE[0]}")/useragents.txt | tail -1)

  curl https://www.google.com/search?q=$i \
    -A "$UA" \
    -s -o $TEMP_DIR/$i.html

  # Random wait time between 0.6 and 2.6 seconds
  RAN=$(printf "0.%2d" $((((1 + RANDOM % 10) * 200)+600)))
  sleep $RAN
done

echo $TEMP_DIR
